version: 2
sources:
  - name: public
    description: "Raw data loaded from the ETL process into the public schema of the data warehouse."
    database: "{{ env_var('DB_NAME', target.database) }}" # Use env var or fallback to target
    schema: public
    tables:
      - name: campaign_performance_raw_appends
        description: "Append-only table containing daily marketing campaign performance metrics from the Volka API."
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: campaigns_execution_date
            description: "The date for which the campaign performance metrics are recorded."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: date
          - name: campaign_name
            description: "Name of the marketing campaign."
            data_tests:
              - not_null
          - name: ad_name
            description: "Name of the ad creative or ad set. Defaults to 'N/A' by the ETL if not provided by the API."
            data_tests:
              - not_null
          - name: spend_cents
            description: "Advertising spend for the campaign on the execution date, in cents."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              # The ETL script replaces negative values with 0, so spend should always be non-negative.
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: impressions
            description: "Number of times the ad was shown."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: clicks
            description: "Number of clicks on the ad."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: registrations
            description: "Number of user registrations attributed to the campaign."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: ctr
            description: "Click-Through Rate (clicks / impressions), calculated by the source system."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: numeric
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: cr
            description: "Conversion Rate (e.g., registrations / clicks), calculated by the source system."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: numeric
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: cpc_cents
            description: "Cost Per Click, in cents."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: players_1d
            description: "Number of unique players active 1 day after install/registration."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between: {min_value: 0}
          - name: payers_1d
            description: "Number of unique paying players 1 day after install/registration."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between: {min_value: 0}
          - name: payments_1d
            description: "Total number of payments made 1 day after install/registration."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between: {min_value: 0}
          - name: revenue_1d_cents
            description: "Total revenue generated 1 day after install/registration, in cents."
            data_tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between: {min_value: 0}
          - name: players_3d
            description: "Number of unique players active 3 days after install/registration."
          - name: payers_3d
            description: "Number of unique paying players 3 days after install/registration."
          - name: payments_3d
            description: "Total number of payments made 3 days after install/registration."
          - name: revenue_3d_cents
            description: "Total revenue generated 3 days after install/registration, in cents."
          - name: players_7d
            description: "Number of unique players active 7 days after install/registration."
          - name: payers_7d
            description: "Number of unique paying players 7 days after install/registration."
          - name: payments_7d
            description: "Total number of payments made 7 days after install/registration."
          - name: revenue_7d_cents
            description: "Total revenue generated 7 days after install/registration, in cents."
          - name: players_14d
            description: "Number of unique players active 14 days after install/registration."
          - name: payers_14d
            description: "Number of unique paying players 14 days after install/registration."
          - name: payments_14d
            description: "Total number of payments made 14 days after install/registration."
          - name: revenue_14d_cents
            description: "Total revenue generated 14 days after install/registration, in cents."
          - name: _etl_loaded_at
            description: "Timestamp of when the record was loaded by the ETL process."
            data_tests:
              - not_null
