version: 2

sources:
  # This defines the existing source from your Python ETL script.
  - name: raw_data_source
    # Use the 'main' schema for the DuckDB target, and 'public' for all others.
    schema: "{{ 'main' if target.name == 'duckdb_iceberg' else 'public' }}"
    tables:
      - name: campaign_performance_raw_appends
        description: "Raw, append-only marketing performance data from the external API."
        columns:
          - name: campaigns_execution_date
            tests:
              - not_null
          - name: campaign_name
            tests:
              - not_null