{%- doc -%}
This snapshot creates a Type 2 Slowly Changing Dimension (SCD) table for campaign performance data.
It tracks the history of changes to key performance metrics over time.

- Strategy: `check` is used to detect changes by comparing the values in the `check_cols` list.
  When a change is detected, the existing record is end-dated and a new record is inserted.
- Unique Key: A surrogate key is generated by combining the natural keys (date, campaign, ad)
  to uniquely identify each campaign ad performance record for a given day.
- Hard Deletes: `invalidate_hard_deletes` is enabled to handle cases where records are removed
  from the source data, ensuring they are marked as invalidated in the snapshot.
{%- enddoc -%}

{% snapshot scd_campaign_performance %}

{{
    config(
      target_schema='snapshots',
      -- A robust surrogate key uniquely identifying a campaign-ad record for a specific day.
      -- This is generated from the natural keys of the source data.
      unique_key='campaign_performance_unique_id',

      -- 'check' strategy compares specified columns to detect changes.
      strategy='check',
      -- All performance and financial metrics to monitor for historical changes.
      -- If any of these columns change for a given unique_key, a new version will be snapshotted.
      check_cols=[
        'spend_cents', 'impressions', 'clicks', 'registrations', 'ctr', 'cr', 'cpc_cents',
        'players_1d', 'payers_1d', 'payments_1d', 'revenue_1d_cents',
        'players_3d', 'payers_3d', 'payments_3d', 'revenue_3d_cents',
        'players_7d', 'payers_7d', 'payments_7d', 'revenue_7d_cents',
        'players_14d', 'payers_14d', 'payments_14d', 'revenue_14d_cents'
      ],
      -- If a record is removed from the source, this will mark the corresponding
      -- snapshot record as invalid, rather than leaving it as the current version.
      invalidate_hard_deletes=True,
    )
}}

-- Select the raw data and generate a robust unique key for the snapshot.
select
    {{ dbt_utils.generate_surrogate_key([
        'campaigns_execution_date',
        'campaign_name',
        'ad_name'
    ]) }} as campaign_performance_unique_id,
    *
from {{ source('raw_data', 'campaign_performance_raw_appends') }}

{% endsnapshot %}