name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Get pip cache directory
        id: pip-cache-dir
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }} # Use the pip cache directory
          # Create a cache key based on the hash of all requirements files.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt
          pip install -r requirements-dev.txt # Install development dependencies

      - name: Lint with flake8 and black
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black . --check

      - name: Lint with sqlfluff
        run: |
          sqlfluff lint dbt_project/

      - name: Run Python Unit Tests
        run: |
          pytest tests/

      - name: Run dbt tests
        env:
          DBT_DB_HOST: localhost # Matches service name
          DBT_DB_USER: test_user # Matches service config
          DBT_DB_PASSWORD: test_password # Matches service config
          DBT_DB_NAME: test_db # Matches service config
          DBT_DB_PORT: 5432 # Matches service config
        run: |
          dbt deps --profiles-dir dbt_project/ --project-dir dbt_project/
          dbt build --profiles-dir dbt_project/ --project-dir dbt_project/